-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 12 Oca 2024, 10:09:09
-- Sunucu sürümü: 10.4.32-MariaDB
-- PHP Sürümü: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `tarifler`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `tarif`
--

CREATE TABLE `tarif` (
  `tarif_id` int(11) NOT NULL,
  `baslik` varchar(100) NOT NULL,
  `malzeme` varchar(1000) NOT NULL,
  `icerik` varchar(5000) NOT NULL,
  `resim` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_turkish_ci;

--
-- Tablo döküm verisi `tarif`
--

INSERT INTO `tarif` (`tarif_id`, `baslik`, `malzeme`, `icerik`, `resim`) VALUES
(1, 'Krep2', '2 adet yumurta 2 su bardağından biraz az un 2 su bardağı süt 1 çay kaşığı tuz pişirmek için tereyağı veya sıvı yağ', 'Krep tarifi hazırlamak için un, süt ve suyu karıştırma kabına alarak hiç topak kalmayana kadar iyice çırpın. Yumurtaları ekleyin biraz daha çırpın.Teflon tavaya 1 çay kaşığı kadar tereyağı veya sıvı yağ koyup fırça ile yayın.                    Kızgın tavaya 1 kepçe krep hamuru dökün, sağa sola eğerek yayın.                    Her iki tarafını çevirerek hafif kızarana kadar orta ateşte pişirin afiyet olsun.', 'menemen.jpg'),
(2, 'Menemen', '2 yemek kaşığı zeytinyağı 2 yemek kaşığı tereyağı 3 adet orta boy domates 4 adet orta boy sivri biber 3 adet yumurta 1 çay kaşığı tuz 1/2 çay kaşığı karabiber 1/2 çay kaşığı pul biber', '2 yemek kaşığı zeytinyağı ve 2 yemek kaşığı tereyağını kızdırın.Üzerine 3 adet doğranmış yeşil biberi katın ve kavurun. Kavrulan biberlerin üzerine 3 adet rendelenmiş domatesi ilave edin.1 çay kaşığı tuzu ve yarımşar çay kaşığı karabiber ve pul biberi katıp suyu azalana kadar pişirin.                    Domates suyunu biraz çektikten sonra 3 adet yumurtanın beyazını menemen harcının içerisine ekleyin ve sürekli olarak karıştırın.                    Yumurtanın beyazları piştikten sonra sarısını da üzerine ilave edine ve 1 dakika karıştırdıktan sonra ocaktan alın.Afiyet olsun.', 'menemen.jpg'),
(3, 'Patatesli Omlet', '3 adet patates 3 adet yumurta 1 çay kaşığı tuz 4 yemek kaşığı sıvı yağ', 'Patatesleri rendeleyelim.Üzerine yumurtaları, tuzu ekleyerek kaşık yardımı ile karıştıralım.Yapışmaz tavamıza 2 kaşık sıvı yağı koyalım.Tavamız ısındıktan sonra patatesli harcımızı tavaya dökelim.Ardından tavamızın kapağını kapatalım ve kısık ateşte kontrollü bir şekilde 10-15 dakika kadar pişmeye bırakalım.Sürenin sonunda spatula ile omletimizin kenarından kaldıralım ve pişip pişmediğini kontrol edelim.Tek tarafı pişen omletimizi bir kapak yardımı ile ters çevirelim.Kapağa aldığımız patatesi dikkatli bir şekilde tekrar tavaya alalım. Tavanın kapağını kapatalım ve kısık ateşte yaklaşık 15 dakika kadar pişmeye bırakalım.İlk 10 dakikadan sonra pişip pişmediğini kontrol edelim. Servis tabağına aldıktan sonra servis edelim. Afiyet olsun.', 'patatesliomlet.jpg'),
(4, 'Pişi', '4,5 su bardağı un 2 silme tatlı kaşığı tuz 1 paket instant maya 2 tatlı kaşığı şeker 1 su bardağı ılık süt 1,5 su bardağı ılık su', 'Yoğurma kabımıza unu alalım, üzerine tuzu ekleyerek karıştıralım.İnstant mayayı, şekeri, ılık sütü ve suyu ekleyerek yoğurmaya başlayalım.Temiz bir bez örterek 60 dakika kadar mayalanmaya bırakalım.Mayası gelen hamurumuzu un serptiğimiz tezgahın üzerine alalım ve biraz daha yoğurarak havasını alalım ve şekil verelim.Şekil verdiğimiz pişilerimizi kızdırdığımız yağa alalım ve çevirerek arkalı önlü kızarana kadar pişirelim.Afiyet olsun.', 'pisi.jpg'),
(5, 'Peynirli Börek', '6 adet yufka Peynir Maydanoz Yarım su bardağı eritilmiş tereyağı 1 su bardağı sıvı yağ 1 su bardağı süt 1 adet yumurta', 'İlk olarak böreğin sosu hazırlanır.Bunun için; uygun bir karıştırma kabına süt, sıvı yağ, eritilmiş tereyağı ve yumurta alınarak karıştırılır.Daha sonra fırın tepsisi üzerine 1 tane yufka açılır.Hazırlanan sostan yufkanın üzerine sürülür. Bir yufka parçalara ayrılarak tepsiye serilir.Üzerine birkaç çeşit peynir ve maydanozdan oluşan iç harçtan konur. Peynirli katlara sos dökmüyoruz.Üzerine parçalara ayrılmış yufka serilerek hazırlanan sostan tekrar bolca sürülür. Bir kat daha 3 parçaya ayrılmış yufka serilir.Peynirli harçtan serpilir. Üzerine bir kat daha yufka serilir. Hazırlanan sostan sürülür.Üzerine bir kat yufka serilir, sostan sürülür. Son peynirli katımız için yufka serilir peynirler serpilir ve üzerine kalan yufka serilir.Tepsinin kenarlarından sarkan yufkalar üzerine kapatılarak börek dilimlenir. Üzerine susam serpilerek sonrasında 180 derece fırında altı üstü kızarana kadar yaklaşık 40 dakika pişirilir.Afiyet olsun.', 'peynirliborek.jpg'),
(6, 'Pizza Börek', '2,5 adet yufka 1 adet yeşil biber 1 adet kırmızı biber 1 adet domates 100 gr sucuk 200 gr kaşar peyniri 2 çay kaşığı kekik 1 çay kaşığı pul biber', 'Böreğimizin iç harcı için kırmızı, yeşil biberi ve domatesi doğrayalım ve derin bir karıştırma kabına alalım.                    Kaşar peynirini ve sucu da  küp küp doğrayalım, diğer malzemelerin üzerine ekleyelim.                    Kekik ve pul biberi de ekledikten sonra güzelce karıştıralım.                    4 veya 6 eşit parça böldüğümüz yufkalardan her birine iç harcımızdan yerleştirelim, kenarlarını içe doğru katladıktan sonra sıkı olmayacak şekilde saralım.                    Şekillendirdiğimiz yufkalarımızı önce çırpılmış yumurtaya ardından galeta ununa bulayarak bir tabak içerisine alalım.                    Pişirmek için tavaya sıvı yağı alalım, kızdıktan sonra böreklerimizi tavaya alalım ve iki yüzeyini de güzelce kızartalım.                    Pişen böreklerimizi sıcak sıcak servis edelim. Afiyet olsun!', 'pizzaborek.jpg'),
(7, 'Sigara Böreği', '3 adet yufka 3 adet patates 1 tatlı kaşığı tuz 1 çay kaşığı pul biber 1 çay kaşığı karabiber', 'İç harç için patatesleri haşlayın. Yumuşayan patatesleri alın ve suyunu süzün.                    Geniş bir kaba alın. Üzerine baharat ve tuzu ekleyin. Patates eziciyle ezip püre haline getirin.Yufkaları 8 eşit parçaya bölün.                    Elde edilen üçgenlerin geniş kısmına iç harçtan koyun. İki yanından kapatarak sıkıca rulo şeklinde sarın.                    Sardığınız ruloların uç kısmının pişerken açılmaması için küçük bir kaseye koyduğunuz suya batırın.                    Tüm yufkalar bitene kadar bu şekilde hazırlayın.                    Yağı kızdırdıktan sonra börekleri çevirerek kızartın.                    Kızaran börekler havlu kağıt üzerine alın. Afiyet olsun.', 'sigaraboregi.jpeg'),
(8, 'Ispanaklı Börek', '1 paket yufka 500gr ıspanak 1 adet soğan 250gr ezine peyniri yarım çay kaşığı tuz yarım çay kaşığı karabiber 1 adet yumurta sarısı 1 çay bardağı sıvıyağ 1 çay bardağı süt', 'Ispanakları yıkayıp,süzdükten sonra ince ince doğrayın. İçine ezilmiş peynir ,                    küp küp doğranmış soğanı ve baharatları ekleyip harmanlayın.                    Bir kasede sıvıyağ ve sütü karıştırın. Yufkanızı ortadan ikiye yarım ay şeklinde kesin.                    Fırça yardımıyla sostan yufkaya yayıp sürün.                    Düz tarafına harcınızı boylu boyunca dizin.                    Sıkı sıkı sararak rulo yapın. Rulonuzu da kendi etrafında sarın ve yağlanmış fırın kabınızın tam ortasına koyun.                    Geri kalan yufkaları da aynı şekilde yapıp,etrafına dolayın. Üzerine yumurta sarısı sürüp,çörek otu serpip fırına verin.                    180 derecede kızarana kadar 20-30 dakika arası kontrollü bir şekilde pişirin.                    Ardından çıkarıp biraz dinlendirin ve dilimleyerek servis edin. Afiyetler olsun!', 'ispanakliborek.jpg'),
(9, 'Mercimek Çorbası', '2 su bardağı kırmızı mercimek1 adet soğan 2 yemek kaşığı un 1 adet havuç Yarım yemek kaşığı biber ya da  domates salçası 1 tatlı kaşığı tuz Yarım çay kaşığı karabiber 1 çay kaşığı kimyon (isteğe bağlı) 2 litre sıcak su 5 yemek kaşığı sıvı yağ', 'Kırmızı mercimek çorbası için sıvı yağı tencereye alınarak yemeklik doğranan soğanlar hafif pembeleşinceye kadar kavrulur.Daha sonra un ilave edilerek kısık ateşte kavurmaya devam edilir.Salça kullanılacak ise salça ilave edilir, kavrulduktan sonra küp küp doğranmış havuç ve iyice yıkanıp suyu süzülen mercimekler ilave edilir.Üzerine su eklenerek karıştırılır ve tencerenin kapağı kapatılır. Çorbamız kaynayana kadar orta ateşte, kaynadıktan sonra mercimekler ve havuçlar yumuşayana kadar ara ara karıştırılarak kısık ateşte pişirilir.Çorba piştikten sonra el blenderı ile güzelce ezilir. Eğer blenderiniz yoksa süzgeçten de geçirebilirsiniz.Karabiber, tuz ve isteğe bağlı olarak kimyon eklenir ve karıştırılır. 5 dakika daha pişirilerek ocaktan alınır.Kıvamı koyu gelirse size, bir miktar su ilave edilerek bir taşım kaynatılır.Bu arada küçük bir tavaya iki yemek kaşığı tereyağı alınır, kızdırılır ve bir tatlı kaşığı kırmızı toz biber eklenerek ocaktan alınır.Mercimek çorbası servis kasesine alındıktan sonra üzerine kırmızı biberli sos gezdirilir ve bir dilim limon ile servis edilir.', 'mercimekcorbasi.jpg'),
(10, 'Yayla Çorbası', '7 su bardağı su 1 su bardağı yoğurt 1 yumurta Yarım fincandan biraz fazla un (Türk kahvesi fincanı) 3 yemek kaşığı sıvı yağ 2 yemek kaşığı tereyağı Tuz Nane', 'Su, sıvı yağ, tuz ve pirinçler tencereye alınır. Pirinçler yumuşayıncaya kadar kaynatılır.                Ayrı bir kasede yoğurt, yumurta ve un, 1 su bardağına yakın su ile birlikte iyice çırpılır.                Pirinçler yumuşayınca hızlıca karıştırarak yoğurtlu karışım çorbaya eklenir. Kaynayana kadar karıştırılır.                 Kaynayınca kısık ateşte 10-15 dk kaynatılır. Ara sıra karıştırmayı ihmal etmeyin.                Çorbamız piştikten sonra altı kapatılır.                Şık bir sunum olması açısından;                Çorba kaselere alınır. Ayrı bir yerde tereyağı kızdırılarak nane ile karıştırılır.                 Ve kaselerdeki çorbaların üzerinde gezdirilir. Kalan naneli tereyağını tenceredeki çorbaya koyup karıştırın.Afiyet olsun.', 'yaylacorbasi.jpeg'),
(11, 'Ezogelin Çorbası', '1 su bardağı kırmızı mercimek 1 tatlı kaşığı pirinç 1 tatlı kaşığı bulgur2 çay kaşığı pul biber 1 yemek kaşığı nane 2 diş sarımsak 1 orta boy soğan 1 yemek kaşığı biber salçası 1 yemek kaşığı tereyağı 2 litreye yakın sıcak su Tuz', 'Ezogelin çorbası yapmak için düdüklü tencerede önce rendelemiş olduğumuz soğanı ve ezmiş olduğumuz sarımsağı tereyağında kavuruyoruz.                Soğanlar diriliğini kaybetsin yeterli yakmadan orta ateşte kavuralım.                Soğanlar kavrulunca naneyi, kırmızı biberi ve salçayı ilave edip. Kavurmaya devam edelim.                Bir iki karıştırdıktan sonra yıkadığımız mercimeği, pirinci, bulguru ve tuzunu da ilave ederek karıştıralım.                Başka bir tarafta kaynamakta olan 2 litreye yakın suyu üzerine boşaltalım.                Düdüklünün kapağını ve düdüğünü kapattıktan sonra 10 dakika pişiriyoruz.Afiyet olsun.', 'ezogelincorbasi.jpg'),
(12, 'Tavuk Suyu Çorba', '2 adet haşlanmış tavuk budu 3 yemek kaşığı şehriye 2 yemek kaşığı zeytinyağ 2 yemek kaşığı yoğurt 1.5 yemek kaşığı un 1 adet yumurtanın sarısı 2 diş rendelenmiş sarımsak 1/2 (yarım) adet limon (yarım) 1 çay kaşığı karabiber 1 tatlı kaşığı tuz 8-9 su bardağı su (tavuğun kendi suyunu da kullanıyoruz)', 'Önce tavukları haşlıyoruz.Terbiyesini hazırlıyoruz un,yoğurt,yumurtayı bir kapta çırpıyoruz.İçine yarım su bardağı su ilave edip iyice pütürsüz olacak şekilde çırpıyoruz.                Haşlanmış tavuğun suyundan sıcak olarak içine üç kepçe kadar alıp terbiyeyisine ilave edip iyice çırpıyoruz.                Çorbayı hazırlayacağım tencereye sıvı yağ ilave ediyoruz şehriyeyi hafif rengi dönmeden kavuruyoruz.                Sarımsağı rendeleyip içine ilave ediyoruz suyunu ilave ediyoruz.                Parçalanmış tavukları ilave ediyoruz bir taşım hepsini kaynatıyoruz.                Çorbanın içine terbiyesini ilave ediyoruz bir taşım kaynatıyoruz.                İçine yarım sıkılmış limon suyunu ve tuzunu ilave ederek çorbamızı bir taşım daha kaynatıyoruz. Kıvam alınca ocağı kapatıyoruz.            Afiyet olsun.', 'tavuksuyucorbasi.jpg'),
(13, 'Fırında Tavuk ', 'Tavuk Zeytinyağı Baharatlar', 'Tavukları baharatlarla harmanlayın, zeytinyağı ekleyin. Fırında pişirin.', 'tavuk1.jpg'),
(14, 'Mantarlı Sote', '2 adet orta boy soğan 3 adet yeşil biber 3 diş sarımsak 3 adet domates 500g kültür mantarı 3-4 yemek kaşığı sıvı yağ 1 yemek kaşığı domates salçası 1 çay kaşığı pul biber 1 çay kaşığı tuz 1 tutam maydanoz (isteğe bağlı)', 'Mantar sote için öncelikle soğanları yemeklik olacak şekilde doğrayın.                Yeşil biber ve sarımsakları da minik minik doğrayın.                Domateslerin kabuklarını soyarak, onları da küp küp doğrayın.                Mantarların kabuklarını soyarak onları da ince ince dilimleyelim.                Tencereye bir miktar sıvı yağı  koyup doğranan soğan, biber ve sarımsakları 1-2 dakika kavurun.                Ardından üzerine S-salça ve pul biberi ekleyerek 1-2 dakika daha kavurun.                İnce ince dilimlenmiş mantarları ilave edip karıştırın. Mantarlar suyunu salıp çekinceye kadar pişirmeye devam edin.                Karıştırılarak bir süre pişirildikten sonra doğranmış domatesleri ve tuzu ekleyerek yemek suyunu çekip, mantarlar yumuşayana  kadar pişirin.                Mantar sotemiz servise hazır.Afiyet olsun.', 'mantarlisote.jpg'),
(15, 'Sultan Kebabı', '2 adet yufka 400g tavuk göğsü 400g tavuk pirzola 1 adet kuru soğan 1 su bardağı haşlanmış ya da konserve bezelye 1 adet patlıcan 1 yemek kaşığı domates salçası (Birazını ketçap kullanabilirsiniz) Pul biber Kekik Karabiber Tuz 1,5 yemek kaşığı un 1,5 su bardağı süt 2 yemek kaşığı tereyağı Tuz Kaşar peyniri rendesi', 'Patlıcanı alacalı soyarak küçük küçük doğrayın ve sıvı yağ ile kızartın.                Süzgece alarak yağının süzmesi bekleyin bu arada tavukları soteleyin.                Tavukları kuş başı doğrayın, tencereye alarak arada karıştırarak pişirin.                Rengi dönüp suyunu saldığında yemeklik doğranmış soğanı ekleyin.                Soğanlar yumuşadıktan sonra salçayı ve isteğe bağlı kullanacaksanız eğer ketçabı ilave edin.                Kapağını kapatarak 4-5 dk. kadar pişmeye bırakın.                Suyunu çektikten sonra bezelye ve patlıcanı ilave edin.                Baharatları da ekleyerek 3-4 dk. daha pişirin.                Beşamel sos için, tereyağını eritin ve unu kokusu çıkana kadar kavurun.                Üzerine sütü ilave ederek çırpıcı yardımı ile topak kalmayacak şekilde koyulaşıp göz göz olana kadar karıştırarak pişirin.                Son olarak tuzunu ilave ederek ocaktan alın.                Küçük bir kaseye 4’e böldüğünüz yufkadan serin.                Yufkanın kenarlarından parçalar kopartarak çukur olan kısma bir kat daha serin.                Kaseye tavuklu harçtan koyarak, kasenin kenarlarından sarkan yufkaları üzerine kapatın.                Yağlanmış fırın kabına ters çevirin.                Tüm malzemeyi bu şekilde yaptıktan sonra üzerleri beşamel sostan her birine eşit miktarda olacak şekilde dökün.                190 derece fırında yufkalar pembeleşene kadar pişirin.                Sonra üzerine kaşar peyniri rendesi serpin ve tekrar fırına sürün.                Peynirler eriyip kızardığında alabilirsiniz.Afiyet olsun.', 'sultankebabi.jpg'),
(16, 'Biber Dolması', 'Yarım kg dolmalık biber Her biber için 1 yemek kaşığı pirinç 1 adet soğan 1 yemek kaşığı salça Maydanoz 2-3 adet domates Karabiber Tuz Nane Sıvı yağ-Zeytinyağı', 'Dolmalık biberlerimizi temizleyelim. Soğanları, domatesi küçük küçük doğrayalım.Domatesin kenarlarını biberlerin üstünü kapatmak için kullanacağız o yüzden önce kapatmak için kullanacaklarımızı kesersek daha iyi olur.                İçini yemek harcında kullanabiliriz.                Bir kaba hazırladığımız soğan, pirinç, salça, maydanoz, domates, karabiber, tuz, nane ve çok az sıvı yağı ekleyip iyice karıştıralım.                Daha sonra bu harcı biberlere dolduralım.                Harcı doldurduğumuz biberleri, tencereye dizelim.                Harcı yaptığımız kabın içine sıcak su koyalım.                O artık göz kararı olacak biberlerin yarısına kadar gelecek şekilde kabın içine koyduğumuz suya 1 yemek kaşığı salça ekleyelim ve eritelim.                Bu karışımı biberlerin üstüne gelmeyecek şekilde tencereye, biberlerin yarısına gelene kadar dökelim.                Kestiğimiz domateslerle biberlerin üstünü kapatalım.Daha sonra biberlerin üstüne çok az sıvı yağ veya zeytinyağı gezdirelim.Kısık ateşte yemeğimizi pişirelim.Afiyet olsun.', 'biberdolmasi.jpg'),
(17, 'Mozaik Kek', '3 adet yumurta 1 su bardağı şeker 1 su bardağından az sıvı yağ 1 su bardağı süt 2 su bardağı un 1 paket kabartma tozu 1 paket vanilya 1 yemek kaşığı kakao', 'Uygun bir karıştırma kabına yumurta ve şekeri alarak, yumurtalar beyazlaşıp köpük köpük oluncaya kadar çırpalım.                Ardından süt ve sıvı yağı ilave edelim ve karıştıralım.                Un, kabarma tozu ve vanilyayı karışımın üzerine eleyelim ve çırpmaya devam edelim.                Hazırladığımız kek harcından 1 su bardağı kadarını ayıralım.                Kalan harcı pişirme kağıdı yerleştirdiğimiz baton kalıba dökelim.                Ayırdığımız harca kakao ekleyerek hamurumuzu karıştıralım.                Kek kalıbının üzerine kakaolu kek hamurunu dökelim ve çöp şiş ya da kürdan yardımı ile S şekli çizerek şekil verelim.                Kekimizi önceden ısıttığımı 160 derece fırında yaklaşık 50 dakika pişmeye bırakalım. Bu aşamada kekinize kürdan testi yapıp piştiğinden emin olduktan sonra fırından alabilirsiniz.                İlk sıcaklığı çıkan mozaik kekimizi kalıptan çıkartalım. Soğuduktan sonra dilimleyerek servis edelim. Afiyet olsun.', 'mozaikkek.jpg'),
(18, 'Elmalı Kurabiye', '3 su bardağı un 250 gram oda ısısında tereyağı veya margarin1 yemek kaşığı yoğurt 1 çay kaşığı kabartma tozu 1 limon kabuğu rendesi (isteğe bağlı) 1 kahve fincanı pudra şekeri 3 elma orta boy elma rendesi 1 tatlı kaşığı tarçın 1 küçük boy çay bardağı şeker 1 avuç dövülmüş ceviz (isteğe bağlı, yaklaşık yarım su bardağı)', 'Rendelenen elma, tarçın ve şeker küçük bir tencereye alınıp orta ateşte elmalar suyunu salıp çekene kadar pişirilir ve soğumaya bırakılır.                Soğuyunca istenirse ceviz de konulur.                Ayrı bir yoğurma kabında un hariç hamur malzemelerini alarak elimizle güzelce karıştıralım.                Ardından yavaş yavaş un ilavesiyle birlikte ele yapışmayacak yumuşak bir kıvamda yoğrulur. Unu çok fazla ekleyerek hamurunuzu sertleştirmemelisiniz.                Yoğrulan hamur tezgaha alınarak eşit 5 bezeye ayrılır. Bezeler avuç içerisinde yuvarlanır.                Bezelerden biri tezgaha alınır. Altı üstü unlanarak tatlı tabağı büyüklüğünde, yarım cm kalınlığında olacak şekilde açılır.                Açılan hamur önce dörde, her bir parça da 2 ye bölünür. (Yani toplam 8 üçgen çıkacak).                Geniş kısımlarına soğuyan elma harcından 1 tatlı kaşığı koyularak, sigara böreği sarar gibi sarılır. Her beze için aynı işlem sırasıyla uygulanır.                Şekil verilen kurabiyeler pişirme kağıdı serili tepsiye dizilir.                Önceden ısıtılmış 170 derece fırında 20 dakika kadar pişirilir.                Kurabiyelerin altı hafif kızardığı anda fırından alınır.Elmalı kurabiyeler ılınınca üzerine pudra şekeri serpilir ve servis edilir. Afiyet olsun.', 'elmalikurabiye.jpg'),
(19, 'Sütlaç', '1 lt süt 2 çay bardağı pirinç 1 litre su 3 yemek kaşığı pirinç unu 1,5 -2 su bardağı toz şeker (eğer çok şekerli sevmiyorsanız 1,5 bardak kullanabilirsiniz) 1 su bardağı süt tarçın', 'Sütlaç yapmak için öncelikle pirinci yıkayıp su ile ateşe koyun.                Pirinçler uzayıp suyu çekene kadar kaynatın. Ocağı çok yüksek ateşte açarak pirinçleri yakmamaya dikkat edin.                Ardında soğuk sütü ekleyin. 1-2 defa karıştırıp, kaynamasını bekleyin.                Bu arada bir kasede pirinç ununu 1 su bardağı soğuk süt ile ezin. Topak kalmamasına mutlaka dikkat edin.                Tencerede kaynamakta olan sütten 1-2 kepçe alıp kaseye ekleyin. (pirinç unu ılınmış olmalı).                Pirinç ununu tencereye ekleyin, ara sıra karıştırarak 10 dakika kadar pişirin.                Toz şekeri ilave edip karıştırın ve 1-2 taşım daha kaynatın.                Sütlacı kaselere paylaştırın.                Soğuyunca sütlaçların üzerlerine tarçın serperek servis edebilirsiniz. Afiyet olsun.', 'sutlac.jpg'),
(20, 'Şekerpare', '125 gram oda ısısında margarin Yarım su bardağı pudra şekeri 3 çorba kaşığı silme irmik 1 adet yumurta 2,5 su bardağı un 1 paket vanilya 1 çay kaşığı silme kabartma tozu 1 çay bardağı fındı  2 su bardağı şeker 3 su bardağı su 4-5 damla limon suyu', 'Karıştırma kabına yağı, pudra şekerini koyup karıştırıyoruz.Yumurtayı ilave edip tekrar karıştırıyoruz İrmiği, kabartma tozunu, vanilyayı ve unu azar azar ilave ederek kulak memesi yumuşaklığında hamur elde ediyoruz.                Hamurdan cevizden biraz büyük parçalar kopartıp elimizle yuvarlıyoruz.                Üzerini çok hafif düzleyip ortalarına birer bütün fındık içi yerleştiriyoruz.                Yağlanmış fırın tepsisine diziyoruz.                180 derece önceden ısıtılmış fırında üzeri altın sarısı rengini alana kadar yaklaşık 30 dakika pişiriyoruz.                 Şerbet için derin tencereye suyu ve şekeri koyup yaklaşık 10-15 dakika arası pişiriyoruz.                 İndirmeye yakın limon suyunu ekliyoruz 2-3 dakika daha pişiriyoruz.                Pişen şerbeti ılınmaya bırakıyoruz.                Pişen şekerpareleri fırından alıp 2 dakika kadar bekletip ılık şerbeti üzerine kepçe yardımı ile gezdiriyoruz.Afiyet olsun.', 'sekerpare.jpg');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `tarif`
--
ALTER TABLE `tarif`
  ADD PRIMARY KEY (`tarif_id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `tarif`
--
ALTER TABLE `tarif`
  MODIFY `tarif_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
